/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forum;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author student
 */
public class okno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(okno.class.getName());

    /**
     * Creates new form okno
     */
    public okno() {
        initComponents();
        setLocationRelativeTo(null);
        pnlRegistracija.setVisible(false);
        pnlPrijava.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPozdrav = new javax.swing.JLabel();
        pnlRegistracija = new javax.swing.JLayeredPane();
        lblUporabnik = new javax.swing.JLabel();
        txtUporabnik = new javax.swing.JTextField();
        lblMail = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        lblGeslo = new javax.swing.JLabel();
        txtGeslo = new javax.swing.JTextField();
        btnPotrdi = new javax.swing.JButton();
        pnlPrijava = new javax.swing.JLayeredPane();
        lblUporabnik1 = new javax.swing.JLabel();
        txtUporabnik1 = new javax.swing.JTextField();
        lblGeslo1 = new javax.swing.JLabel();
        txtGeslo1 = new javax.swing.JTextField();
        btnPrijava = new javax.swing.JButton();
        btnRegistracija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblPozdrav.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPozdrav.setText("Pozdravljen gost!");

        pnlRegistracija.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registracija", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlRegistracija.setPreferredSize(new java.awt.Dimension(350, 250));

        lblUporabnik.setText("Uporabnik");
        lblUporabnik.setMinimumSize(new java.awt.Dimension(60, 25));
        lblUporabnik.setPreferredSize(new java.awt.Dimension(60, 25));

        txtUporabnik.setPreferredSize(new java.awt.Dimension(200, 30));

        lblMail.setText("E-mail");
        lblMail.setPreferredSize(new java.awt.Dimension(60, 25));

        txtMail.setPreferredSize(new java.awt.Dimension(200, 30));

        lblGeslo.setText("Geslo");
        lblGeslo.setPreferredSize(new java.awt.Dimension(60, 25));

        txtGeslo.setPreferredSize(new java.awt.Dimension(200, 30));

        btnPotrdi.setText("Potrdi");
        btnPotrdi.setPreferredSize(new java.awt.Dimension(200, 25));
        btnPotrdi.addActionListener(this::btnPotrdiActionPerformed);

        pnlRegistracija.setLayer(lblUporabnik, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlRegistracija.setLayer(txtUporabnik, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlRegistracija.setLayer(lblMail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlRegistracija.setLayer(txtMail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlRegistracija.setLayer(lblGeslo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlRegistracija.setLayer(txtGeslo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlRegistracija.setLayer(btnPotrdi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlRegistracijaLayout = new javax.swing.GroupLayout(pnlRegistracija);
        pnlRegistracija.setLayout(pnlRegistracijaLayout);
        pnlRegistracijaLayout.setHorizontalGroup(
            pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistracijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPotrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlRegistracijaLayout.createSequentialGroup()
                            .addComponent(lblUporabnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtUporabnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlRegistracijaLayout.createSequentialGroup()
                            .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlRegistracijaLayout.createSequentialGroup()
                            .addComponent(lblGeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtGeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlRegistracijaLayout.setVerticalGroup(
            pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistracijaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUporabnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUporabnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPotrdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnlPrijava.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prijava", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlPrijava.setPreferredSize(new java.awt.Dimension(350, 250));

        lblUporabnik1.setText("Uporabnik");
        lblUporabnik1.setPreferredSize(new java.awt.Dimension(60, 25));

        txtUporabnik1.setPreferredSize(new java.awt.Dimension(200, 30));

        lblGeslo1.setText("Geslo");
        lblGeslo1.setPreferredSize(new java.awt.Dimension(60, 25));

        txtGeslo1.setPreferredSize(new java.awt.Dimension(200, 30));

        btnPrijava.setText("Prijava");
        btnPrijava.setPreferredSize(new java.awt.Dimension(100, 25));
        btnPrijava.addActionListener(this::btnPrijavaActionPerformed);

        btnRegistracija.setText("Registracija");
        btnRegistracija.setPreferredSize(new java.awt.Dimension(100, 25));
        btnRegistracija.addActionListener(this::btnRegistracijaActionPerformed);

        pnlPrijava.setLayer(lblUporabnik1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlPrijava.setLayer(txtUporabnik1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlPrijava.setLayer(lblGeslo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlPrijava.setLayer(txtGeslo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlPrijava.setLayer(btnPrijava, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlPrijava.setLayer(btnRegistracija, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlPrijavaLayout = new javax.swing.GroupLayout(pnlPrijava);
        pnlPrijava.setLayout(pnlPrijavaLayout);
        pnlPrijavaLayout.setHorizontalGroup(
            pnlPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrijavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrijavaLayout.createSequentialGroup()
                        .addComponent(lblUporabnik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUporabnik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrijavaLayout.createSequentialGroup()
                        .addComponent(lblGeslo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGeslo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrijavaLayout.createSequentialGroup()
                        .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlPrijavaLayout.setVerticalGroup(
            pnlPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrijavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUporabnik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUporabnik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeslo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeslo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnlPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPozdrav)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPozdrav))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPotrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotrdiActionPerformed
        // TODO add your handling code here:
        String uporabnik = txtUporabnik.getText();
        String mail = txtMail.getText();
        String geslo = txtGeslo.getText();
        try {
            PrintWriter pw = new PrintWriter(new FileWriter("C:\\Rac4\\uporabnik.txt" ,  true));
            pw.println(uporabnik);
            pw.println(mail);
            pw.println(geslo);
            pw.close();
            lblPozdrav.setText("Pozdravljen " + uporabnik + "!");
            pnlRegistracija.setVisible(false);
        }
        catch (IOException e){
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
    }//GEN-LAST:event_btnPotrdiActionPerformed

    private void btnRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistracijaActionPerformed
        // TODO add your handling code here:
        pnlPrijava.setVisible(false);
        pnlRegistracija.setVisible(true);
    }//GEN-LAST:event_btnRegistracijaActionPerformed

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        // TODO add your handling code here:
        try{
            String uporabnik = txtUporabnik1.getText();
            BufferedReader br = new BufferedReader(new FileReader("C:\\Rac4\\uporabnik.txt"));
            String upDat = br.readLine();
            while(upDat != null){
                if(uporabnik.equals(upDat)){
                    br.readLine();
                    String gDat = br.readLine();
                    if(gDat.equals(txtGeslo1.getText())){
                        lblPozdrav.setText("Pozdravljen " + uporabnik + "!");
                        return;
                    }
                    else{
                        JOptionPane.showMessageDialog(this , "Napačno geslo");
                        txtGeslo1.setText("");
                        txtGeslo1.requestFocusInWindow();
                        return;
                    }
                }
                br.readLine();
                br.readLine();
                upDat = br.readLine();
            }
            JOptionPane.showMessageDialog(this,"Ni takega uporabnika, registriraj se!");
            txtUporabnik1.setText("");
            txtGeslo1.setText("");
        }
        catch(IOException e){
            
        }
    }//GEN-LAST:event_btnPrijavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new okno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPotrdi;
    private javax.swing.JButton btnPrijava;
    private javax.swing.JButton btnRegistracija;
    private javax.swing.JLabel lblGeslo;
    private javax.swing.JLabel lblGeslo1;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblPozdrav;
    private javax.swing.JLabel lblUporabnik;
    private javax.swing.JLabel lblUporabnik1;
    private javax.swing.JLayeredPane pnlPrijava;
    private javax.swing.JLayeredPane pnlRegistracija;
    private javax.swing.JTextField txtGeslo;
    private javax.swing.JTextField txtGeslo1;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtUporabnik;
    private javax.swing.JTextField txtUporabnik1;
    // End of variables declaration//GEN-END:variables
}
